apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ingestion-pipeline
spec:
  workspaces:
    - name: source
  params:
    - default: '{{ .Values.defaults.git.url }}'
      description: Repo URL
      name: GIT_URL
      type: string
    - default: '{{ .Values.defaults.git.script }}'
      description: The location of the python script containing the kfp pipeline
      name: KFP_SCRIPT
      type: string
    - default: '{{ .Values.defaults.git.path }}'
      description: The direcotry of the KFP_SCRIPT
      name: PATH_CONTEXT
      type: string
    - default: '{{ .Values.defaults.git.revision }}'
      name: GIT_REVISION
      type: string
    - default: {{ .Values.defaults.python_image | default "3.11-ubi9" }}
      name: PYTHON_IMAGE
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/dspa'
      name: TARGET_IMAGE
      type: string
    - default: 'https://ds-pipeline-dspa-{{ .Release.Namespace }}.{{ $.Values.clusterDomain }}'
      name: KUBEFLOW_ENDPOINT
      type: string
    - name: PRODUCT_LOAD
      description: Product to load
      default: "red_hat_openshift_ai_self-managed"
    - name: PRODUCT_FULL_NAME
      description: Product full name to load
      default: "Red Hat OpenShift AI Self-Managed"
    - name: PRODUCT_VERSION
      description: Product version to load
      default: "2.14"
    - name: PRODUCT_LANG
      description: Product lang to load
      default: "en-US"
  tasks:
    - name: git-clone
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: REVISION
          value: $(params.GIT_REVISION)
        # - name: gitInitImage
        #   value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:868966ef9d4b54952d8a74eb83bba40eb1f52c0148994fa704efd0e3797c61c5'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: source
    - name: s2i-python
      params:
        - name: VERSION
          value: $(params.PYTHON_IMAGE)
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: IMAGE
          value: $(params.TARGET_IMAGE)
      runAfter:
        - git-clone
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: s2i-python
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: source
    - name: execute-kubeflow-pipeline
      params:
        - name: IMAGE
          value: $(params.TARGET_IMAGE)
        - name: TAG
          value: latest
        - name: SCRIPT
          value: $(params.KFP_SCRIPT)
        - name: KUBEFLOW_ENDPOINT
          value: $(params.KUBEFLOW_ENDPOINT)
        - name: PRODUCT_LOAD
          value: $(params.PRODUCT_LOAD)
        - name: PRODUCT_FULL_NAME
          value: $(params.PRODUCT_FULL_NAME)
        - name: PRODUCT_VERSION
          value: $(params.PRODUCT_VERSION)
        - name: PRODUCT_LANG
          value: $(params.PRODUCT_LANG)
      runAfter:
        - s2i-python
      taskRef:
        kind: Task
        name: execute-kubeflow-pipeline