apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: execute-website-ingestion-kubeflow-pipeline
spec:
  description: >-
    This task will execute a python script, triggering a kubeflow pipeline
  params:
    - name: IMAGE
      description: The image used to execute the script
      type: string
    - name: TAG
      description: The tag for the image
      type: string
      default: "latest"
    - name: SCRIPT
      description: The location of the script to be executed
    - name: KUBEFLOW_ENDPOINT
      description: The endpoint URL for Kubeflow
      default: "https://ds-pipeline-dspa:8443"
    - name: WEBSITE_URL
      description: The website url to be ingested
      default: "https://www.redhat.com/en/topics/containers/red-hat-openshift-okd"      
    - name: VECTORDB_INDEX
      description: The vector db index where the website scrape to be ingested
      default: "WebScrapedData"
  steps:
    - name: execute-python
      image: $(inputs.params.IMAGE):$(inputs.params.TAG)
      env:
        - name: WEBSITE_URL
          value: $(inputs.params.WEBSITE_URL)
        - name: VECTORDB_INDEX
          value: $(inputs.params.VECTORDB_INDEX)          
        - name: KUBEFLOW_ENDPOINT
          value: $(inputs.params.KUBEFLOW_ENDPOINT)
        - name: BASE_IMAGE
          value: $(inputs.params.IMAGE):$(inputs.params.TAG)
        - name: CLUSTER_DOMAIN
          value: '{{ $.Values.clusterDomain }}'
      script: |
        python $(inputs.params.SCRIPT)